---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: elastic/oel-7-x86_64

suites:
  - name: default
    run_list:
      - recipe[centroid_oracle_db::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      oracle_db:
        user:
          pw_set: True
        rdbms:
          dbbin_version: 12c
